### PR TITLE
Support Discogs

### LINKED ISSUE #30: Support New Site: Discogs

### PR DESCRIPTION
**Pull request by qilinz**
Test added. 

Need to add a `DISCOGS_TOKEN` in `settings.py` to get image from discogs API.
- token can be generated on https://www.discogs.com/settings/developers
- a [personal access token](https://www.discogs.com/developers/#page:authentication) is enough.

close #30

### CODE REVIEW

**Comment by qilinz** [comment]
FYI I have upgraded Python to 3.11

**Comment by qilinz** [comment]
I see that the test failed because of the token. May I ask what's the current way of Neodb to manage token? Is there an existing way to collaborating on the token part?

I can set an empty str in the settings.py if no other ways around

**Comment by alphatownsman** [comment]
If need be, I can set the token in Github Action's test env settings. However, in this case, you may replace `request.get` with `BasicDownloader(url).download().json()`. With this change, you may store response data in test_data/ and the test will run with the cached data as long as you put `@use_local_response` before the test method.

please also add an empty str as default value in settings.py with short comment of how to obtain the token.

**Comment by qilinz** [comment]
Yes, the test data are the ones using downloader consistent with test cases in `tests.py`.

API key updated.

Another issue is that when i run `python3 manage.py test --keepdb`, some errors occurs for other scrapers. Should i care about them? For example: `lxml.etree.ParserError: Document is empty`

**Comment by alphatownsman** [comment]
you may ignore that lxml error or recompile it to get thru, see more in #5

**Pull request merged**
